# Generated by Django 3.1.7 on 2021-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_extension', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('text', 'Text')], default='image', max_length=10)),
            ],
        ),
    ]
