# Generated by Django 3.1.7 on 2021-05-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfileapp', '0004_auto_20210511_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extension',
        ),
    ]
